build App:
  image: golang
  script:
    - go mod tidy
    - go run github.com/DapperBlondie/service-monitor/cmd/web -dbuser='dapperblondie' -pusherHost='localhost:4001' -pusherSecret='123abc' -pusherKey='abc123' -pusherSecure=false -pusherApp="1" -db="monitor"