development:
  dialect: postgres
  database: monitor
  user: dapperblondie
  password: dapperblondie
  host: localhost
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://dapperblondie:dapperblondie@127.0.0.1:5432/monitor_test"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://dapperblondie:dapperblondie@127.0.0.1:5432/monitor_production"}}